//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles.
        /// </summary>
        internal static string CirclePlural {
            get {
                return ResourceManager.GetString("CirclePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string EquilateralTriangle {
            get {
                return ResourceManager.GetString("EquilateralTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangles.
        /// </summary>
        internal static string EquilateralTrianglePlural {
            get {
                return ResourceManager.GetString("EquilateralTrianglePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Shapes report&lt;/h1&gt;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Empty list of shapes!&lt;/h1&gt;.
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        internal static string Perimeter {
            get {
                return ResourceManager.GetString("Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles.
        /// </summary>
        internal static string RectanglePlural {
            get {
                return ResourceManager.GetString("RectanglePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares.
        /// </summary>
        internal static string SquarePlural {
            get {
                return ResourceManager.GetString("SquarePlural", resourceCulture);
            }
        }
    }
}
